version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: twitter_clone_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ./web/server/.env
    volumes:
      - twitter_postgres_data:/bitnami/postgresql
    networks:
      - twitter_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: twitter_clone_pgadmin
    restart: unless-stopped
    ports:
      - "5050:5050"
    env_file:
      - ./web/server/.env
    volumes:
      - twitter_pgadmin_data:/var/lib/pgadmin
    networks:
      - twitter_network
    depends_on:
      - postgres

volumes:
  twitter_postgres_data:
    driver: local
  twitter_pgadmin_data:
    driver: local

networks:
  twitter_network:
    driver: bridge
