services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: twitter_clone_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ./packages/server/.env
    volumes:
      - twitter_postgres_data:/bitnami/postgresql
    networks:
      - twitter_network

volumes:
  twitter_postgres_data:
    driver: local

networks:
  twitter_network:
    driver: bridge
